### ISSUE TITLE
Visual glitch for some vanilla blocks

### ISSUE THREAD

**Issue by ThePizza1k** [grondag/Pyroclasm#4] opened 2018-10-15 01:01 UTC
A strange visual glitch with black texture across the side of grass blocks and for leaves is occurring with this mod. Does not seem to affect gameplay. Moves when the player turns or moves. If the player is facing without up or down direction, then the texture will form vertical lines.
![image](https://user-images.githubusercontent.com/44148753/46924560-0b19a500-cff4-11e8-9649-aa3cb36cb413.png)

**Comment by grondag** [comment] 2018-10-15 01:05
Thank you for the bug report.  Unfortunately I'm not seeing this in any of my runs.

Can you tell me what other mods are present and what versions of OS and Forge you are using?

**Comment by ThePizza1k** [comment] 2018-10-15 01:28
14.23.4.2705 1.12.2 for forge, OS is windows 10 update 1803. Only present mods are Pyroclasm and dependencies. 

EDIT: Also present in forge 1.12.2 14.23.5.2768

**Comment by wormzjl** [comment] 2018-10-16 18:11
Same issue here.
I'm using windows 7, forge 2768.
For further info:
jre1.8.0_181
GTX 1080

**Comment by grondag** [comment] 2018-10-16 20:13
Thank you both for the details.  That hardware should be fine and it doesn't appear to be a mod compatibility problem.  One other thing that may help:

In your log during startup you should see this message
`[Acuity Rendering API]: Acuity Rendering API can run on this hardware. VBOs, shaders and OpenGL 2.1 are all supported.`

If you aren't seeing that, please post your log so I can look for other errors.

I have a windows box here and will try to reproduce as soon as I wrap up a couple other bug fixes in progress.  Ran fine on Windows before but may have made some updates since then that borked it up.

**Comment by wormzjl** [comment] 2018-10-17 08:31
Yes I do have this message in my log

**Comment by grondag** [comment] 2018-10-19 22:09
Fixed in Acuity.  Will be released this weekend.
https://github.com/grondag/Acuity/issues/5

**Closed as completed by grondag** 2018-10-19 22:09 UTC
Labels: bug
